# Generated by Django 3.2.6 on 2021-09-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0007_rename_order_placed_shopcart_paid_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='order_code',
            new_name='cart_code',
        ),
    ]
