# Generated by Django 3.2.7 on 2021-09-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0008_rename_order_code_shopcart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
