# Generated by Django 3.2.7 on 2021-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img.jpeg', upload_to='Category/'),
        ),
    ]
