# Generated by Django 3.2.7 on 2021-09-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0011_paidorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='card_code',
            new_name='cart_code',
        ),
    ]
